version: '3.8'

services:
  web:
    build: .
    container_name: backend_web_1
    ports:
      - "8000:8000"
    volumes:
      # Монтируем базу иuploads наружу на хост, чтобы данные были бессмертными
      - ./uploads:/app/uploads
      - ./chetmedia.db:/app/chetmedia.db
    env_file:
      - .env
    restart: always